---
title: "vaginal pH analyses"
author: "Rachel Petersen"
date: "11/5/2021"
output: html_document
---

```{r}
library(robustlmm)
library(lmerTest)
library(car)
library(sjPlot)
library(ggeffects)
library(XML)
library(multcomp)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(lmtest)
library(RColorBrewer)
```

#read in the data
```{r}
pH_data <- read.csv("pH_data.csv")
```

#modeling effect of cycle phase on pH
```{r}
#remove postcopulatory samples and relevel
pH_noPostcop <- pH_data %>%
  filter(Postcop == "N")
pH_noPostcop$phase <- relevel(as.factor(pH_noPostcop$phase), ref = "non-fertile")

#robust linear model
robust_mod <- rlmer(Avg.pH ~ phase + Avg.temp + (1|FemaleID), data=pH_noPostcop)
mod_results<-as.data.frame(summary(robust_mod)$coefficients)

#calculate pvalue for robust model
output<-tab_model(robust_mod, show.p=TRUE);output
mod_df<-data.frame(readHTMLTable(htmlParse(output), h=T))
pvalues <- mod_df[2:6,4]
mod_results$pvalue<-pvalues

write.table(mod_results[-1,], "pH_phase_modresult.txt", quote=F, sep="\t")
```

#plot results (SI Fig)
```{r}
#generate model predictions
dat <- ggpredict(robust_mod, terms=c("phase"))
dat<- data.frame(dat)
dat.tidy <- dat %>%
  mutate(stder.high = (predicted + std.error)) %>%
  mutate(stder.low = (predicted - std.error))

#plot model predictions + raw data
pH_phase_plot <- ggplot(data= dat, aes(x=x, y=predicted)) +
  geom_point(aes(color=x),size=3) +
  geom_errorbar(aes(ymin=stder.low, ymax=stder.high, color=x), width=0.1, linewidth=1.5) +
  scale_color_manual(values=c("#0076BA", "#FEAE00" , "#FF644E", "#73BFFA")) +
  geom_jitter(data= pH_noPostcop, aes(x=phase, y=Avg.pH), width=0.25, size=0.4, alpha=0.5)+
  theme_bw() +
  scale_x_discrete(labels = c("non-fertile", "pre-fertile", "fertile", "post-fertile")) +
  theme(plot.title= element_blank(), axis.text.y=element_text(size=12, color="black"), axis.text.x=element_text(size=12, angle=45, hjust=1, color="black"),  axis.title=element_text(size=14), legend.position="none") +
  xlab("") +
  ylab("Vaginal pH"); pH_phase_plot 
```

#modeling effect of copulation on pH
```{r}
#filter for post-cop samples and non-cop samples from the same females and phases
Postcop_ph<-subset(pH_data, Postcop == "Y") 
Noncop_ph<-subset(pH_data, Postcop == "N" & (phase == "pre-fertile" | phase == "fertile") & (FemaleID == "Suzon" | FemaleID == "Salade" | FemaleID == "Sottise" | FemaleID == "Vertige" | FemaleID == "Vuei"))
pH_postcop_tidy<-rbind(Postcop_ph, Noncop_ph)

#robust linear model
robust_mod2 <- rlmer(Avg.pH ~ Postcop + phase + Avg.temp + (1|DyadID), data=pH_postcop_tidy)
mod2_results<-as.data.frame(summary(robust_mod2)$coefficients)

#calculate pvalue for robust model
output<-tab_model(robust_mod2, show.p=TRUE);output
mod_df<-data.frame(readHTMLTable(htmlParse(output), h=T))
pvalues <- mod_df[2:5,4]
mod2_results$pvalue<-pvalues

write.table(mod6_results[-1,], "pH_postcop_modresult.txt", quote=F, sep="\t")
```


#plot the results (Fig 2E)
```{r}
#generate model predictions
dat <- ggpredict(robust_mod2, terms=c("Postcop"))
dat<- data.frame(dat)
dat.tidy <- dat %>%
  mutate(stder.high = (predicted + std.error)) %>%
  mutate(stder.low = (predicted - std.error))

#plot model predictions + raw data
pH_postcop_plot <- ggplot(data= dat.tidy, aes(y=predicted, x= x)) +
    geom_jitter(data= pH_postcop_tidy, aes(x=Postcop, y=Avg.pH), width=0.2, size=0.5, alpha=0.5)+
  geom_point(aes(color=x),size=2) +
  geom_errorbar(aes(ymin=stder.low, ymax=stder.high, color=x), width=0.1, size=1) +
  scale_color_manual(values= c("#531B93", "#D783FF")) +
  theme_light() +
  theme(plot.title= element_blank(), legend.position= "none") +
  scale_x_discrete(labels= c("N"= "No", "Y"= "Yes")) +
  xlab("Post-copulatory status") +
  ylab("Vaginal pH"); pH_postcop_plot 
```

#heteroscedasicity test
```{r}
mod2 <- lmer(Avg.pH ~ Postcop + phase + Avg.temp + (1|DyadID), data=pH_postcop_tidy)
residuals<-resid(mod2)
fitted_values <- fitted(mod2)
lm_model <- lm(residuals ~ fitted_values)

# Perform Breusch-Pagan test
bptest(lm_model)
```

#Figure 2F
```{r}
mean_data_grouped <- pH_postcop_tidy %>%
  group_by(FemaleID, Postcop) %>%
  summarize(MeanValue = mean(Avg.pH))

pH_postcop_female_plot <- ggplot(data= pH_postcop_tidy, aes(x=Postcop, y=Avg.pH, color=FemaleID)) +
  geom_line(data= mean_data_grouped, aes(x=Postcop, y=MeanValue, group=FemaleID, color=FemaleID), size=1) +
  geom_jitter(data= pH_postcop_tidy, aes(x=Postcop, y=Avg.pH), width=0.1, size=0.5)+
  theme_light() +
  scale_color_brewer(palette = "Set1", labels=c("Salade" = 3, "Sottise" = 5, "Suzon"=6, "Vertige" = 7, "Vuei" = 9), name="Female ID")+
  scale_x_discrete(labels = c("No", "Yes")) +
  theme(plot.title= element_blank()) +
  xlab("Post-copulatory Status") +
  ylab("Vaginal pH"); pH_postcop_female_plot 
```


# modeling the effect of genotype on post-cop pH
```{r}
genotypes<-c("Male_stMLH", "Male_MHCI_allele", "Male_MHCII_allele", "Male_MHCI_supertype", "Male_MHCII_supertype", "KINSHIP", "MHCI_allele_comp", "MHCII_allele_comp", "MHCI_supertype_comp", "MHCII_supertype_comp")
full_mod_results<-as.data.frame(matrix(NA, nrow=0, ncol=5))
simple_mod_results<-as.data.frame(matrix(NA, nrow=0, ncol=5))

for (genotype in genotypes){
   
full <- as.formula(paste("Avg.pH ~ Postcop*", genotype, "+ phase  + Avg.temp + (1|DyadID)"))
full_mod_rob<- rlmer(full, data = pH_postcop_tidy)
full_results<-as.data.frame(summary(full_mod_rob)$coefficients)

output<-tab_model(full_mod_rob, show.p=TRUE);output
full_results$p<-data.frame(readHTMLTable(htmlParse(output), h=T))[2:7,4]

full_results$Genotype<- genotype

full_mod_results <- rbind(full_mod_results, full_results)

}

full_mod_results$Predictors<-rownames(full_mod_results)
Fullmod_interactions<-full_mod_results %>%
  filter(str_detect(Predictors, "^PostcopY:"))

Fullmod_interactions$padj<-p.adjust(Fullmod_interactions$p, method="holm")

write.table(Fullmod_interactions, "pH_genotype_modelresults.txt", quote=F, sep="\t")
```

#KINSHIP plot (Fig 4A)
```{r}
kinship_mod<- rlmer(Avg.pH ~ Postcop* KINSHIP + phase  + Avg.temp + (1|DyadID), data = pH_postcop_tidy)

#generate model predictions
dat <- ggpredict(kinship_mod, terms=c("KINSHIP [all]", "Postcop"))
dat<- data.frame(dat)
dat.tidy <- dat %>%
  mutate(stder.high = (predicted + std.error)) %>%
  mutate(stder.low = (predicted - std.error))

KIN_pH_oneplot <- ggplot(data= dat.tidy, aes(y=predicted, x= group, color=x, group=x)) +
  geom_point(position=position_dodge(width=0.8), size=3) +
  geom_errorbar(aes(ymin = stder.low, ymax = stder.high, linetype=NULL, group=x), width=0.3, padding=0.3, position=position_dodge(width=0.8), size=1) +
    theme_bw(14) +
  theme(plot.title=element_text(size=16, hjust=0.5)) +
    geom_point(data= na.omit(pH_postcop_tidy), aes(x=Postcop, y=Avg.pH, color=KINSHIP, group=KINSHIP), size=2, shape= 21, position=position_dodge(width=0.8)) + 
   scale_color_gradient2(low = "grey1", mid= "grey40", high = "grey80", name= "Kinship", trans= "reverse", limits= c(0.25, -0.25), breaks= c(0.2, 0.1, 0, -0.1, -0.2), labels= c(0.2, 0.1, 0, -0.1, -0.2))+
  ylab("Vaginal pH") +
  xlab("Post-copulatory Status") +
  ggtitle("Kinship") +
  scale_x_discrete(labels=c("No", "Yes"));KIN_pH_oneplot
```


#MHCII allele comp plot (Fig 4B)
```{r}
mhc2allele_mod <- rlmer(Avg.pH ~  Postcop*MHCII_allele_comp + phase + Avg.temp + (1|MaleID)+ (1|FemaleID), data=pH_postcop_tidy)

dat <- ggpredict(mhc2allele_mod, terms=c("MHCII_allele_comp [all]", "Postcop"))
dat<- data.frame(dat)
dat.tidy <- dat %>%
  mutate(stder.high = (predicted + std.error)) %>%
  mutate(stder.low = (predicted - std.error))


MHCII_allele_comp_pH_oneplot <- ggplot(data= dat.tidy, aes(y=predicted, x= group, color=x, group=x)) +
  geom_point(position=position_dodge(width=0.6), size=3) +
  geom_errorbar(aes(ymin = stder.low, ymax = stder.high, linetype=NULL, group=x), width=0.3, position=position_dodge(width=0.6), size=1) +
    theme_bw(14) +
  theme(plot.title=element_text(size=16, hjust=0.3)) +
    geom_point(data= na.omit(pH_postcop_tidy), aes(x=Postcop, y=Avg.pH, color=MHCII_allele_comp, group=MHCII_allele_comp), size=1.8, shape=21, position=position_dodge(width=0.6)) +
   scale_color_gradient2(high = "grey1", mid= "grey40", low="grey80", midpoint= 0.5, name= "Proportion \nshared \nalleles", breaks=c(0,0.2,0.4,0.6,0.8,1.0), limits=c(-0.05, 1.05)) +
  guides(color = guide_colorbar(reverse=T)) +
  ylab("Vaginal pH") +
  xlab("Post-copulatory Status") +
  ggtitle("MHC II allelic complementarity") +
  scale_x_discrete(labels=c("No", "Yes"));MHCII_allele_comp_pH_oneplot
```


#MHCII supertype comp plot (Fig 4C)
```{r}
mhc2super_mod <- rlmer(Avg.pH ~  Postcop*MHCII_supertype_comp + phase + Avg.temp + (1|MaleID) + (1|FemaleID), data=pH_postcop_tidy)

dat <- ggpredict(mhc2super_mod, terms=c("MHCII_supertype_comp [all]", "Postcop"))
dat<- data.frame(dat)
dat.tidy <- dat %>%
  mutate(stder.high = (predicted + std.error)) %>%
  mutate(stder.low = (predicted - std.error))


MHCII_supertype_comp_pH_oneplot <- ggplot(data= dat.tidy, aes(y=predicted, x= group, color=x, group=x)) +
geom_point(position=position_dodge(width=0.8), size=3) +
  geom_errorbar(aes(ymin = stder.low, ymax = stder.high, linetype=NULL, group=x), width=0.3, position=position_dodge(width=0.8), size=0.7) +
    theme_bw(14) +
  theme(plot.title=element_text(size=16, hjust=0.3)) +
    geom_point(data= na.omit(pH_postcop_tidy), aes(x=Postcop, y=Avg.pH, color=MHCII_supertype_comp, group=MHCII_supertype_comp), size=1.5, shape=21, position=position_dodge(width=0.8)) +
   scale_color_gradient2(high = "grey0", mid= "grey40", low="grey80", midpoint= 0.5, name= "Proportion \nshared \nsupertypes", breaks=c(0,0.2,0.4,0.6,0.8,1.0), limits=c(-0.05, 1.05)) +
  guides(color = guide_colorbar(reverse=T)) +
  ylab("Vaginal pH") +
  xlab("Post-copulatory Status") +
  ggtitle("MHC II supertype complementarity") +
  scale_x_discrete(labels=c("No", "Yes"), expand=expansion(mult=.2));MHCII_supertype_comp_pH_oneplot
```
